/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type { DaoFactoryAbi, DaoFactoryAbiInterface } from "../DaoFactoryAbi";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_signer",
        type: "address",
      },
      {
        internalType: "address",
        name: "_signerVerification",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "dao",
        type: "address",
      },
      {
        indexed: false,
        internalType: "address",
        name: "creator",
        type: "address",
      },
    ],
    name: "DAOCreated",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "string",
        name: "name",
        type: "string",
      },
      {
        internalType: "string",
        name: "symbol",
        type: "string",
      },
      {
        internalType: "string",
        name: "_commonURI",
        type: "string",
      },
      {
        internalType: "string",
        name: "_rareURI",
        type: "string",
      },
      {
        internalType: "string",
        name: "_legendaryURI",
        type: "string",
      },
    ],
    name: "createDAO",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class DaoFactoryAbi__factory {
  static readonly abi = _abi;
  static createInterface(): DaoFactoryAbiInterface {
    return new utils.Interface(_abi) as DaoFactoryAbiInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): DaoFactoryAbi {
    return new Contract(address, _abi, signerOrProvider) as DaoFactoryAbi;
  }
}
