export * from './heading-four.component'
export * from './heading-one.component'
export * from './heading-three.component'
export * from './heading-two.component'
export * from './paragraph.component'
